### ISSUE TITLE
v0.0.1 Release checklist

### ISSUE THREAD

**Issue by damar-wicaksono** [damar-wicaksono/uqtestfuns#142]
Release v0.1.0 is imminent. Here are few things that must be modified once/just before the release is submitted to PyPI:

- [x] Update the README with a correct way of obtaining the package
- [x] Update the "Obtaining and Installing UQTestFuns" in the docs
- [ ] ~Register the package either in ROBIS or Zenodo to obtain the DOI~ (defer to v0.1.0)
- [ ] ~Add the DOI badge in the README.md~ (defer to v0.1.0)
- [x] Finalize the CHANGELOG

**Comment by damar-wicaksono** [comment]
The DOI badge will not be issued until you make you first release

**Comment by damar-wicaksono** [comment]
This issue has been resolved. v0.0.1 has been released!
