### ISSUE TITLE
Implement the McLain test functions

### ISSUE THREAD

**Issue by damar-wicaksono** [damar-wicaksono/uqtestfuns#189]
Implement all the test functions that appear in McLain's 1974 paper[^McLain1974]. The implementation should be put in a single module. Most of the functions are actually similar to four of the six Franke's test functions[^Franke1979]. The latter slightly modify the function and translates the inputs to $[0, 1]$ (instead of the original $[1, 10]$:

- [x] S1: a part of sphere (resolved by PR #193)
- [x] S2: A steep hill rising from a plain (resolved by PR #194)
- [x] S3: A less steep hill (resolved by PR #195)
- [x] S4: A long narrow hill (resolved by PR #196)
- [x] S5: A plateau and plain separated by a steep cliff (resolved by PR #192)

[^Franke1979]:  Richard Franke, A critical comparison of some methods for interpolation of scattered data, Technical Report No. NPS53-79-003, Naval Postgraduate School, Monterey, Canada, 1979.  [URL](https://core.ac.uk/reader/36727660).
[^McLain1974]:  D. H. McLain, Drawing contours from arbitrary data points, The Computer Journal, vol. 17, no. 4, pp. 318-324, 1974. [DOI: 10.1093/comjnl/17.4.318](https://doi.org/10.1093/comjnl/17.4.318)

**Comment by damar-wicaksono** [comment]
This issue has been resolved by a series of PR's (#192, 193, 194, 195, 196, and 197). Closing this issue.
