### ISSUE TITLE
Reorganize all Franke test functions inside a single module

### ISSUE THREAD

**Issue by damar-wicaksono** [damar-wicaksono/uqtestfuns#191]
It may make more sense to put all (six) Franke test functions inside a single module to avoid duplication on the probabilistic input specification. All input specifications for each test function are identical. 

While we're at it, implement the rest of the Franke test functions:

- [x] (1st) Franke function: Two Gaussian peaks and a Gaussian dip on a surface slopping down toward upper right boundary (resolved by PR #185)
- [x] (2nd) Franke function: Two nearly flat regions joined by a sharp rise running diagonally (resolved by PR #190)
- [x] (3rd) Franke function: A saddle shaped surface (resolved by PR #188)
- [x] (4th) Franke function: A Gaussian hill that slopes off in a gentle fashion (resolved by PR #198)
- [x] (5th) Franke function: A steep Gaussian hill which becomes almost zero at the boundaries (resolved by PR #199)
- [x] (6th) Franke function: A part of sphere above the unit square (resolved by PR #200)

**Comment by damar-wicaksono** [comment]
This issue has been resolved by a series of PR's (#185, #190, #188, #198, #199, #200).
