### ISSUE TITLE
Implement a CI pipeline using GitHub actions

### ISSUE THREAD

**Issue by damar-wicaksono** [damar-wicaksono/uqtestfuns#35]
A CI pipeline for building and testing the package should be implemented using GitHub actions.

**Comment by damar-wicaksono** [comment]
Create a single workflow with the following jobs:

- [ ] Formatting (using black #37)
- [ ] Linting (using flake8 #39)
- [ ] Type checking (using #24)
- [ ] Testing
- [ ] Building wheels
- [ ] Building source distribution

**Comment by damar-wicaksono** [comment]
MR #36 added the code formatting to the CI pipeline.

**Comment by damar-wicaksono** [comment]
MR #41 added a linter using flake8 to the CI pipeline.

**Comment by damar-wicaksono** [comment]
PR #42 added automatic testing using pytest to the CI pipeline.

**Comment by damar-wicaksono** [comment]
PR #43 added automatic static type checking using mypy to the CI pipeline.

**Comment by damar-wicaksono** [comment]
PR #44 added automatic wheel and sdist building using the `build` package to the CI pipeline.

**Comment by damar-wicaksono** [comment]
PR #168 includes GitHub action to publish automatically released package (tagged with semantic versioning) to PyPI.

This issue, therefore, can be closed.
